# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Robot Framework CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
          # Install additional dependencies if needed
          pip install -r requirements.txt

    - name: Install browser dependencies
      run: |
        rfbrowser init

    - name: Run Robot Framework tests
      run: |
        robot -d Results Tests/API-Tests/e2eTest.robot

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: Results/